services:
  backend:
    build: .
    image: gcf-backend:latest
    ports:
      - "3301:3301"
    environment:
      DB_HOST: gcfpostgres  # nome do container do PostgreSQL
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    networks:
      - gcf_net

networks:
  gcf_net:
    external: true
